name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    services:
      selenium-hub:
        image: selenium/hub:4.1.0-20211209
        ports:
          - 4444:4444
      chrome:
        image: selenium/node-chrome:4.1.0-20211209
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
        ports:
          - 5900:5900
      firefox:
        image: selenium/node-firefox:4.1.0-20211209
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
        ports:
          - 5901:5900

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium Tests
      run: |
        python test_login.py
      env:
        BROWSER: ${{ matrix.browser }}
        HUB_HOST: selenium-hub
